site_name: 游戏宝库下载
site_url: https://game.zhihu.blog/
site_author: shutouyabo
site_description: >-
  wiki game

repo_name: 游戏宝库
repo_url: https://github.com/shutouyabo/game.zhihu.blog/

copyright: Copyright &copy; 2026 <a href="https://game.zhihu.blog/" target="_blank" rel="noopener noreferrer">游戏宝库下载</a>



theme:
  name: material
  language: zh
  static_templates:
    - 404.html
  favicon: images/favicon.ico
  apple-touch-icon-precomposed: images/mobile_icon.png
  include_search_page: false
  search_index_only: true

  features:
    - header.autohide
    - navigation.tracking
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - content.code.annotate

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: cyan
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to light mode

  font:
    text: Roboto Slab
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github

  custom_dir: overrides

markdown_extensions:
  - attr_list
  - md_in_html
  - footnotes

plugins:
  - i18n:
      languages:
        - locale: zh
          default: true
          name: 简体中文
          build: true

  - search:
      lang:
        - zh
  - git-revision-date:
  - minify:
      minify_html: true
  - open-in-new-tab:

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://v6.51.la/land/L0ZDlWY6HhH0NxKi
  analytics:
    provider: google
    property: G-KJB4RXSKZG

nav:
  - 前言: "index.md"
  - PC游戏:
      - "1 动作冒险": "PC游戏/1 动作冒险.md"
      - "2 策略战略": "PC游戏/2 策略战略.md"
      - "3 国风仙侠": "PC游戏/3 国风仙侠.md"
      - "4 肉鸽游戏": "PC游戏/4 肉鸽游戏.md"
      - "5 竞速体育": "PC游戏/5 竞速体育.md"
      - "6 益智休闲": "PC游戏/6 益智休闲.md"
      - "7 模拟经营": "PC游戏/7 模拟经营.md"
      - "8 角色扮演": "PC游戏/8 角色扮演.md"
      - "9 格斗对战": "PC游戏/9 格斗对战.md"
      - "10 枪战射击": "PC游戏/10 枪战射击.md"
      - "11 恐怖惊悚": "PC游戏/11 恐怖惊悚.md"
      - "12 复古经典": "PC游戏/12 复古经典.md"
      - "13 回合战旗": "PC游戏/13 回合战旗.md"
  - 手机游戏:
      - "1 安卓游戏": "手机游戏/1 安卓游戏.md"
      - "2 苹果游戏": "手机游戏/2 苹果游戏.md"



